# Generated by Django 3.2.9 on 2022-01-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_column='name', max_length=200),
        ),
    ]
