# Generated by Django 3.2.12 on 2022-02-25 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integers', '0002_alter_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
