# Generated by Django 3.2.9 on 2022-04-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integers', '0006_auto_20220330_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='fname',
            field=models.CharField(default='fredy', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='lname',
            field=models.CharField(default='fuentes', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='material',
            field=models.CharField(default='wood', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tool',
            field=models.CharField(default='hammer', max_length=200),
        ),
    ]
